"""Phase 6 - Strategy Output & QuantConnect LEAN code generation.

For each accepted strategy we emit a self-contained folder:

    strategies/<ID>/
        main.py               <- QuantConnect LEAN algorithm (ready to run)
        feature_data.csv      <- timestamp, price + the feature columns it needs
        strategy.json         <- machine-readable rule definition
        STRATEGY_REPORT.md    <- entry/exit/risk rules + full backtest + validation

The generated `main.py` follows the standard QuantConnect pattern an experienced
LEAN dev would use:
  * AddFuture(...) for EXECUTION (real, tradable contract),
  * a custom PythonData class that streams the pre-computed structural feature
    CSV for the SIGNAL (so the exact research feature is reproduced live, not
    re-derived approximately),
  * the prop constraints (min-hold seconds, per-trade stop, daily profit cap,
    account & EOD drawdown halt, max contracts) enforced in OnData.
"""
from __future__ import annotations

import json
from pathlib import Path

import pandas as pd

from .backtester import Strategy
from .config import Config
from .features import FeatureSet
from .risk_management import PropConstraints
from .validators import ValidationReport


def _used_features(strat: Strategy) -> list[str]:
    cols = [strat.entry_feature]
    if strat.exit_feature:
        cols.append(strat.exit_feature)
    if strat.filter_feature:
        cols.append(strat.filter_feature)
    # de-dup, preserve order
    seen, out = set(), []
    for c in cols:
        if c and c not in seen:
            seen.add(c)
            out.append(c)
    return out


def export_strategy(report: ValidationReport, feature_set: FeatureSet,
                    config: Config, constraints: PropConstraints,
                    out_root: Path, descriptions: dict | None = None) -> Path:
    strat = report.strategy
    out_dir = out_root / strat.id
    out_dir.mkdir(parents=True, exist_ok=True)

    cols = _used_features(strat)
    # ---- 1. feature_data.csv (signal data for LEAN custom feed)
    data = pd.DataFrame({"price": feature_set.price})
    for c in cols:
        data[c] = feature_set.frame[c]
    data.index.name = "timestamp"
    data.to_csv(out_dir / "feature_data.csv")

    # ---- 2. strategy.json
    payload = {
        "strategy": strat.to_dict(),
        "features_used": cols,
        "feature_descriptions": {c: (descriptions or {}).get(c, "") for c in cols},
        "metrics": report.full,
        "validation": {
            "accepted": report.accepted,
            "in_sample": report.in_sample,
            "out_sample": report.out_sample,
            "walk_forward": report.walk_forward,
            "monte_carlo": report.monte_carlo,
            "robustness": report.robustness,
            "overfitting": report.overfitting,
        },
        "prop_constraints": constraints.__dict__,
        "instrument": config.section("instrument"),
    }
    (out_dir / "strategy.json").write_text(json.dumps(payload, indent=2, default=str),
                                           encoding="utf-8")

    # ---- 3. main.py (LEAN algorithm)
    (out_dir / "main.py").write_text(
        _render_lean_algorithm(strat, cols, config, constraints), encoding="utf-8")

    # ---- 4. STRATEGY_REPORT.md
    (out_dir / "STRATEGY_REPORT.md").write_text(
        _render_report(report, cols, config, constraints, descriptions or {}),
        encoding="utf-8")

    return out_dir


# ==========================================================================
#  LEAN algorithm template
# ==========================================================================
def _render_lean_algorithm(strat: Strategy, cols: list[str], config: Config,
                           c: PropConstraints) -> str:
    instr = config.section("instrument")
    acct = config.section("account")
    symbol = instr.get("symbol", "MES")
    point_value = float(instr.get("point_value", 5.0))

    entry = _py_cond("row", strat.entry_feature, strat.entry_op, strat.entry_threshold)
    filt = ("True" if not strat.filter_feature
            else _py_cond("row", strat.filter_feature, strat.filter_op,
                          strat.filter_threshold))
    has_signal_exit = bool(strat.exit_feature)
    sig_exit = ("False" if not has_signal_exit
                else _py_cond("row", strat.exit_feature, strat.exit_op,
                              strat.exit_threshold))
    direction_long = strat.direction == "long"

    csv_cols = ", ".join(f'"{col}"' for col in cols)

    return f'''# region imports
from AlgorithmImports import *
import numpy as np
# endregion

# ==========================================================================
#  Auto-generated by QC LEAN Bridge  -  Strategy {strat.id}
#  {strat.describe()}
#
#  EXECUTION : {symbol} future (real contract)
#  SIGNAL    : custom line-break structural feature feed (feature_data.csv)
#  PROP RULES: min-hold {c.min_hold_seconds:.0f}s, per-trade stop {min(strat.stop_pct, c.per_trade_max_dd_pct):.2g}%,
#              daily profit cap ${c.daily_profit_cap:.0f}, account DD halt {c.account_max_dd_pct}%,
#              EOD trailing DD ${c.eod_max_drawdown:.0f}, max {c.max_position_contracts} contracts
# ==========================================================================


class StructureFeatureData(PythonData):
    """Streams the pre-computed structural features exported by the research
    framework. Upload feature_data.csv to the QC Object Store / Data folder."""

    COLUMNS = [{csv_cols}]

    def GetSource(self, config, date, isLive):
        # Point this at the uploaded feature_data.csv location.
        return SubscriptionDataSource("feature_data.csv",
                                      SubscriptionTransportMedium.LocalFile)

    def Reader(self, config, line, date, isLive):
        if not line or line[0].isalpha():
            return None
        parts = line.split(",")
        try:
            data = StructureFeatureData()
            data.Symbol = config.Symbol
            data.Time = datetime.strptime(parts[0][:19], "%Y-%m-%d %H:%M:%S")
            data.Value = float(parts[1])        # price
            # map remaining columns by header order
            for i, name in enumerate(StructureFeatureData.COLUMNS):
                data[name] = float(parts[2 + i])
            return data
        except Exception:
            return None


class {_class_name(strat.id)}(QCAlgorithm):

    def Initialize(self):
        self.SetStartDate(2023, 1, 1)
        self.SetEndDate(2024, 12, 31)
        self.SetCash({float(acct.get("starting_equity", 50000.0)):.0f})

        # --- execution instrument (real tradable future) ---
        future = self.AddFuture(Futures.Indices.MicroSP500EMini,
                                Resolution.Second)
        future.SetFilter(0, 90)
        self.future_symbol = future.Symbol
        self.contract = None

        # --- signal feed (custom structural features) ---
        self.feat = self.AddData(StructureFeatureData, "STRUCT",
                                 Resolution.Second).Symbol

        # --- prop constraints ---
        self.MIN_HOLD_SECONDS = {c.min_hold_seconds}
        self.MAX_HOLD_SECONDS = {c.max_hold_seconds}
        self.DAILY_PROFIT_CAP = {c.daily_profit_cap}
        self.PER_TRADE_STOP_PCT = {min(strat.stop_pct, c.per_trade_max_dd_pct)} / 100.0
        self.TARGET_PCT = {strat.target_pct} / 100.0
        self.TIME_EXIT_BARS = {strat.time_exit_bars}
        self.ACCOUNT_DD_DOLLARS = {float(acct.get("starting_equity", 50000.0)) * c.account_max_dd_pct / 100.0}
        self.EOD_MAX_DD = {c.eod_max_drawdown}
        self.MAX_CONTRACTS = {c.max_position_contracts}
        self.CONTRACTS = min({strat.contracts}, self.MAX_CONTRACTS)
        self.POINT_VALUE = {point_value}

        # --- state ---
        self.entry_time = None
        self.entry_price = None
        self.bars_in_trade = 0
        self.start_equity = self.Portfolio.TotalPortfolioValue
        self.peak_equity = self.start_equity
        self.day_peak_equity = self.start_equity
        self.daily_pnl_start = self.start_equity
        self.current_day = None
        self.halted = False
        self.day_halted = False
        self.daily_capped = False

    # ---------------------------------------------------------------- data
    def OnData(self, slice):
        # track the front-month contract for execution
        for chain in slice.FutureChains:
            contracts = sorted(chain.Value, key=lambda x: x.Expiry)
            if contracts:
                self.contract = contracts[0].Symbol

        if self.feat not in slice:
            return
        row = slice[self.feat]

        self._roll_day()
        self._update_risk_flags()

        if self.contract is None:
            return

        invested = self.Portfolio[self.contract].Invested if self.contract in self.Portfolio else False

        if invested:
            self._manage_open(row)
        else:
            self._maybe_enter(row)

    # ------------------------------------------------------------- helpers
    def _roll_day(self):
        d = self.Time.date()
        if d != self.current_day:
            self.current_day = d
            self.day_peak_equity = self.Portfolio.TotalPortfolioValue
            self.daily_pnl_start = self.Portfolio.TotalPortfolioValue
            self.day_halted = False
            self.daily_capped = False

    def _update_risk_flags(self):
        eq = self.Portfolio.TotalPortfolioValue
        self.peak_equity = max(self.peak_equity, eq)
        self.day_peak_equity = max(self.day_peak_equity, eq)
        if (self.peak_equity - eq) >= self.ACCOUNT_DD_DOLLARS:
            self.halted = True
        if self.EOD_MAX_DD > 0 and (self.day_peak_equity - eq) >= self.EOD_MAX_DD:
            self.day_halted = True
        if (eq - self.daily_pnl_start) >= self.DAILY_PROFIT_CAP:
            self.daily_capped = True

    def _maybe_enter(self, row):
        if self.halted or self.day_halted or self.daily_capped:
            return
        if {entry} and {filt}:
            qty = self.CONTRACTS if {direction_long} else -self.CONTRACTS
            self.MarketOrder(self.contract, qty)
            self.entry_time = self.Time
            self.entry_price = self.Securities[self.contract].Price
            self.bars_in_trade = 0

    def _manage_open(self, row):
        self.bars_in_trade += 1
        held = (self.Time - self.entry_time).total_seconds() if self.entry_time else 0
        price = self.Securities[self.contract].Price
        long = {direction_long}

        if long:
            hit_stop = price <= self.entry_price * (1 - self.PER_TRADE_STOP_PCT)
            hit_target = price >= self.entry_price * (1 + self.TARGET_PCT)
        else:
            hit_stop = price >= self.entry_price * (1 + self.PER_TRADE_STOP_PCT)
            hit_target = price <= self.entry_price * (1 - self.TARGET_PCT)

        time_exit = self.TIME_EXIT_BARS > 0 and self.bars_in_trade >= self.TIME_EXIT_BARS
        max_hold = self.MAX_HOLD_SECONDS > 0 and held >= self.MAX_HOLD_SECONDS
        signal_exit = {sig_exit}
        force = self.halted or self.day_halted

        want_exit = hit_stop or hit_target or time_exit or max_hold or signal_exit or force

        # PROP RULE: never close before the minimum hold time
        if want_exit and held >= self.MIN_HOLD_SECONDS:
            self.Liquidate(self.contract)
            self.entry_time = None
            self.entry_price = None
            self.bars_in_trade = 0
'''


def _py_cond(rowvar: str, feature: str, op: str, thr) -> str:
    return f'{rowvar}["{feature}"] {op} {float(thr):.6g}'


def _class_name(sid: str) -> str:
    return "Strategy" + "".join(ch for ch in sid if ch.isalnum())


# ==========================================================================
#  Human-readable Phase 6 report
# ==========================================================================
def _render_report(report: ValidationReport, cols: list[str], config: Config,
                   c: PropConstraints, descriptions: dict) -> str:
    s = report.strategy
    f = report.full
    lines = []
    A = lines.append
    A(f"# Strategy {s.id} - Full Report\n")
    A(f"**Accepted:** {'YES' if report.accepted else 'NO'}")
    if report.reasons:
        A(f"**Rejection reasons:** {'; '.join(report.reasons)}")
    A(f"\n**Rule:** {s.describe()}\n")

    A("## Entry / Exit / Risk Rules")
    A(f"- **Direction:** {s.direction.upper()}")
    A(f"- **Entry:** `{s.entry_feature} {s.entry_op} {s.entry_threshold:.6g}`")
    if s.filter_feature:
        A(f"- **Filter:** `{s.filter_feature} {s.filter_op} {s.filter_threshold:.6g}`")
    if s.exit_feature:
        A(f"- **Signal exit:** `{s.exit_feature} {s.exit_op} {s.exit_threshold:.6g}`")
    A(f"- **Stop loss:** {min(s.stop_pct, c.per_trade_max_dd_pct):.2g}% adverse "
      f"(per-trade DD capped at {c.per_trade_max_dd_pct}%)")
    A(f"- **Profit target:** {s.target_pct:.2g}%")
    if s.time_exit_bars:
        A(f"- **Time exit:** {s.time_exit_bars} bars")
    A(f"- **Position size:** {min(s.contracts, c.max_position_contracts)} contracts "
      f"(prop max {c.max_position_contracts})")
    A(f"- **Min hold:** {c.min_hold_seconds:.0f}s enforced before any exit")

    A("\n## Feature Definitions")
    for col in cols:
        A(f"- **{col}** - {descriptions.get(col, 'engineered structural feature')}")

    A("\n## Prop Firm Compliance")
    A(f"- Min hold time: {c.min_hold_seconds:.0f}-{max(c.min_hold_seconds+1, 11):.0f}s")
    A(f"- Daily profit cap: ${c.daily_profit_cap:.0f}")
    A(f"- Account equity DD halt: {c.account_max_dd_pct}%")
    A(f"- EOD trailing DD: ${c.eod_max_drawdown:.0f}")
    A(f"- Max position: {c.max_position_contracts} contracts")
    A(f"- Consistency (min win rate): {c.min_win_rate*100:.0f}%")

    A("\n## Backtest Performance (full sample)")
    A(_metrics_table(f))

    A("\n## Validation")
    A(f"- **In-sample Sharpe:** {report.in_sample.get('sharpe',0):.3f}")
    A(f"- **Out-of-sample Sharpe:** {report.out_sample.get('sharpe',0):.3f}")
    A(f"- **Overfit degradation:** {report.overfitting.get('degradation',0)*100:.0f}% "
      f"({'FLAGGED' if report.overfitting.get('flag_overfit') else 'ok'})")
    wf = report.walk_forward
    A(f"- **Walk-forward:** {wf.get('windows',0)} windows, "
      f"{wf.get('pct_profitable',0)*100:.0f}% profitable, "
      f"per-window Sharpe {wf.get('per_window_sharpe','-')}")
    mc = report.monte_carlo
    A(f"- **Monte Carlo ({mc.get('runs',0)} runs):** "
      f"{mc.get('pct_profitable',0)*100:.0f}% profitable, "
      f"5th-pct net ${mc.get('p05_net',0):.0f}, "
      f"95th-pct max DD ${mc.get('p95_max_dd',0):.0f}")
    rb = report.robustness
    A(f"- **Parameter stability:** {rb.get('stability',0):.3f} "
      f"(Sharpe under +/-{rb.get('perturb_pct',0):.0f}% perturbation: "
      f"{rb.get('sharpe_variants','-')})")

    A("\n## Deployment")
    A("1. Upload `feature_data.csv` to your QuantConnect project "
      "(Object Store or the project's data folder).")
    A("2. Add `main.py` to the project.")
    A("3. Set the correct future contract / start-end dates in `Initialize`.")
    A("4. Backtest in QuantConnect to confirm parity, then paper/forward test.")
    return "\n".join(lines)


def _metrics_table(f: dict) -> str:
    rows = [
        ("Net profit", f"${f.get('net_profit',0):,.2f}"),
        ("Trades", f"{f.get('trades',0)}"),
        ("Sharpe", f"{f.get('sharpe',0):.3f}"),
        ("Sortino", f"{f.get('sortino',0):.3f}"),
        ("Profit factor", f"{f.get('profit_factor',0):.3f}"),
        ("Win rate", f"{f.get('win_rate',0)*100:.1f}%"),
        ("Avg trade", f"${f.get('avg_trade',0):,.2f}"),
        ("Max drawdown", f"${f.get('max_drawdown',0):,.2f} ({f.get('max_drawdown_pct',0):.1f}%)"),
        ("Recovery factor", f"{f.get('recovery_factor',0):.2f}"),
        ("Ulcer index", f"{f.get('ulcer_index',0):.2f}"),
        ("Equity smoothness", f"{f.get('equity_smoothness',0):.3f}"),
    ]
    out = ["| Metric | Value |", "| --- | --- |"]
    out += [f"| {k} | {v} |" for k, v in rows]
    return "\n".join(out)
